#!/usr/bin/env python3
"""Render saved evaluation episodes into replay videos with worker processes."""

from __future__ import annotations

import argparse
import csv
import os
import sys
import time
from concurrent.futures import ProcessPoolExecutor, as_completed
from pathlib import Path
from typing import Any, Dict, List, Mapping, Optional, Sequence, Tuple


os.environ.setdefault("MPLBACKEND", "Agg")
for variable in (
    "OMP_NUM_THREADS",
    "OPENBLAS_NUM_THREADS",
    "MKL_NUM_THREADS",
    "NUMEXPR_NUM_THREADS",
):
    os.environ.setdefault(variable, "1")


REQUIRED_RENDER_COLUMNS: Tuple[str, ...] = (
    "case_id",
    "map_name",
    "trace_path",
    "trace_meta_path",
    "planned_trajs_path",
    "boundary_offsets_path",
    "refline_xy_path",
    "artifact_dir",
)

SUMMARY_COLUMNS: Tuple[str, ...] = (
    "status",
    "case_id",
    "run_dir",
    "video_path",
    "elapsed",
    "error",
)


RenderRow = Dict[str, str]
ResultRow = Dict[str, Any]
Task = Dict[str, Any]


def clean_name(text: str) -> str:
    """Convert text into a file-name-safe string matching the renderer."""
    for old, new in [("/", "_"), ("\\", "_"), (" ", "_"), (":", "_"), (";", "_"), (",", "_")]:
        text = text.replace(old, new)
    return text


def find_episode_table(run_dir: Path) -> Optional[Path]:
    """Return the first renderer-ready episode table available in one run directory."""
    for path in (
        run_dir / "post_metrics" / "episode_metrics.csv",
        run_dir / "metrics" / "raw_episode_manifest.csv",
    ):
        if path.is_file():
            return path
    return None


def is_run_dir(path: Path) -> bool:
    """Return whether a directory contains an episode table accepted by the renderer."""
    return path.is_dir() and find_episode_table(path) is not None


def discover_run_dirs(input_dir: Path, recursive: bool = False) -> List[Path]:
    """Discover one or more run directories below the requested input path."""
    input_dir = input_dir.resolve()
    if is_run_dir(input_dir):
        return [input_dir]
    if not input_dir.is_dir():
        raise FileNotFoundError(f"Input directory does not exist: {input_dir}")

    candidates = input_dir.rglob("*") if recursive else input_dir.iterdir()
    run_dirs = sorted(path.resolve() for path in candidates if is_run_dir(path))
    if not run_dirs:
        raise FileNotFoundError(f"No renderer-ready run directories found under: {input_dir}")
    return run_dirs


def row_is_ok(row: Mapping[str, Any]) -> bool:
    """Return whether an episode row is eligible for rendering."""
    status = str(row.get("status", "ok")).strip().lower()
    return status in {"", "ok", "success", "true", "1"}


def skipped_result(run_dir: Path, case_id: str, reason: str) -> ResultRow:
    """Build one summary row for an episode skipped before rendering."""
    return {
        "status": "skipped",
        "case_id": case_id,
        "run_dir": str(run_dir),
        "video_path": "",
        "elapsed": 0.0,
        "error": reason,
    }


def load_episode_rows(run_dir: Path) -> Tuple[Path, List[RenderRow], List[ResultRow]]:
    """Load only the episode-table fields consumed by the video renderer."""
    source_csv = find_episode_table(run_dir)
    if source_csv is None:
        raise FileNotFoundError(f"No episode table found for run: {run_dir}")

    valid_rows: List[RenderRow] = []
    skipped_rows: List[ResultRow] = []
    with source_csv.open("r", newline="", encoding="utf-8-sig") as file:
        reader = csv.DictReader(file)
        fieldnames = set(reader.fieldnames or [])
        missing_columns = [name for name in REQUIRED_RENDER_COLUMNS if name not in fieldnames]
        if missing_columns:
            raise ValueError(f"Episode table is missing columns {missing_columns}: {source_csv}")

        for row_index, row in enumerate(reader):
            case_id = str(row.get("case_id", f"row_{row_index}"))
            if not row_is_ok(row):
                skipped_rows.append(
                    skipped_result(run_dir, case_id, f"non-ok status: {row.get('status', '')}")
                )
                continue

            render_row = {name: str(row.get(name, "")) for name in REQUIRED_RENDER_COLUMNS}
            missing_values = [name for name, value in render_row.items() if not value.strip()]
            if missing_values:
                skipped_rows.append(
                    skipped_result(run_dir, case_id, "missing values: " + ", ".join(missing_values))
                )
                continue

            valid_rows.append(render_row)

    return source_csv, valid_rows, skipped_rows


def expected_video_path(row: Mapping[str, Any], video_dir: Path) -> Path:
    """Return the output path generated by render_case_video for one episode."""
    return video_dir / f"{clean_name(str(row['case_id']))}_random_replay.mp4"


def render_one_episode(task: Task) -> ResultRow:
    """Render one episode inside a worker process and return its result row."""
    start = time.perf_counter()
    run_dir = Path(task["run_dir"]).resolve()
    project_root = Path(task["project_root"]).resolve()
    video_dir = Path(task["video_dir"]).resolve()
    row = dict(task["row"])
    overwrite = bool(task["overwrite"])
    case_id = str(row["case_id"])
    output_path = expected_video_path(row, video_dir)

    try:
        video_dir.mkdir(parents=True, exist_ok=True)
        if output_path.is_file() and not overwrite:
            return {
                "status": "skipped",
                "case_id": case_id,
                "run_dir": str(run_dir),
                "video_path": str(output_path),
                "elapsed": 0.0,
                "error": "video already exists",
            }

        if str(project_root) not in sys.path:
            sys.path.insert(0, str(project_root))
        from utils.trace_dashboard import render_case_video

        rendered_path = render_case_video(
            row=row,
            run_dir=run_dir,
            out_dir=video_dir,
            project_root=project_root,
        )
        return {
            "status": "ok",
            "case_id": case_id,
            "run_dir": str(run_dir),
            "video_path": str(rendered_path),
            "elapsed": float(time.perf_counter() - start),
            "error": "",
        }
    except Exception as exc:
        return {
            "status": "error",
            "case_id": case_id,
            "run_dir": str(run_dir),
            "video_path": str(output_path),
            "elapsed": float(time.perf_counter() - start),
            "error": repr(exc),
        }


def build_tasks(
    run_dirs: Sequence[Path],
    project_root: Path,
    out_dir: Path,
    overwrite: bool,
    max_episodes: Optional[int],
) -> Tuple[List[Task], List[ResultRow]]:
    """Build process-pool tasks and collect rows that cannot be rendered."""
    tasks: List[Task] = []
    results: List[ResultRow] = []

    for run_dir in run_dirs:
        source_csv, valid_rows, skipped_rows = load_episode_rows(run_dir)
        results.extend(skipped_rows)
        video_dir = out_dir / run_dir.name / "videos"
        print(
            f"[LOAD] run={run_dir.name} source={source_csv} "
            f"valid={len(valid_rows)} skipped={len(skipped_rows)}"
        )

        for row in valid_rows:
            if max_episodes is not None and len(tasks) >= int(max_episodes):
                return tasks, results
            tasks.append(
                {
                    "run_dir": str(run_dir),
                    "project_root": str(project_root),
                    "video_dir": str(video_dir),
                    "row": row,
                    "overwrite": bool(overwrite),
                }
            )

    return tasks, results


def write_summary_csv(path: Path, rows: Sequence[ResultRow]) -> None:
    """Write one compact CSV containing the result of every episode task."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8-sig") as file:
        writer = csv.DictWriter(file, fieldnames=SUMMARY_COLUMNS)
        writer.writeheader()
        for row in rows:
            writer.writerow({name: row.get(name, "") for name in SUMMARY_COLUMNS})


def parse_args() -> argparse.Namespace:
    """Parse batch-rendering command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Render saved evaluation episodes into replay videos with worker processes."
    )
    parser.add_argument(
        "--input-dir",
        type=Path,
        required=True,
        help="A run directory or a parent directory containing run directories.",
    )
    parser.add_argument(
        "--project-root",
        type=Path,
        default=Path("."),
        help="Project root containing utils/ and players/.",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=Path("results") / "all_episode_videos",
        help="Root output directory for videos and the summary CSV.",
    )
    parser.add_argument(
        "--num-workers",
        type=int,
        default=max(1, (os.cpu_count() or 1) // 2),
        help="Maximum worker-process count.",
    )
    parser.add_argument(
        "--recursive-runs",
        action="store_true",
        help="Search recursively instead of only first-level child directories.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Render episodes even when their output videos already exist.",
    )
    parser.add_argument(
        "--max-episodes",
        type=int,
        default=None,
        help="Maximum total number of episodes submitted for rendering.",
    )
    return parser.parse_args()


def main() -> None:
    """Discover episodes, render them in a process pool, and write the result summary."""
    args = parse_args()
    input_dir = args.input_dir.expanduser().resolve()
    project_root = args.project_root.expanduser().resolve()
    out_dir = args.out_dir.expanduser().resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    run_dirs = discover_run_dirs(input_dir, recursive=bool(args.recursive_runs))
    tasks, results = build_tasks(
        run_dirs=run_dirs,
        project_root=project_root,
        out_dir=out_dir,
        overwrite=bool(args.overwrite),
        max_episodes=args.max_episodes,
    )

    if tasks:
        worker_count = max(1, min(int(args.num_workers), len(tasks)))
        print(f"[INFO] rendering {len(tasks)} episode(s) with {worker_count} worker process(es)")
        with ProcessPoolExecutor(max_workers=worker_count) as executor:
            futures = [executor.submit(render_one_episode, task) for task in tasks]
            for completed, future in enumerate(as_completed(futures), start=1):
                result = future.result()
                results.append(result)
                print(
                    f"[{completed:04d}/{len(tasks):04d}] "
                    f"status={result['status']} case={result['case_id']} "
                    f"elapsed={float(result['elapsed']):.2f}s"
                )
    else:
        print("[WARN] no render tasks were built")

    summary_path = out_dir / "batch_video_render_summary.csv"
    write_summary_csv(summary_path, results)
    print(f"[DONE] summary: {summary_path}")
    print(f"[DONE] videos: {out_dir}")


if __name__ == "__main__":
    main()
